Equibop: Update v3.0.9.tar.gz to 3.0.9

diff --git a/org.equicord.equibop.yml b/org.equicord.equibop.yml
--- a/org.equicord.equibop.yml
+++ b/org.equicord.equibop.yml
@@ -1,153 +1,150 @@
 app-id: org.equicord.equibop
 
 runtime: org.freedesktop.Platform
-runtime-version: &runtime-version "25.08"
+runtime-version: &runtime-version '25.08'
 sdk: org.freedesktop.Sdk
 
 base: org.electronjs.Electron2.BaseApp
 base-version: *runtime-version
 sdk-extensions:
-    - org.freedesktop.Sdk.Extension.node20
+  - org.freedesktop.Sdk.Extension.node20
 
 command: startequibop
 separate-locales: false
 
 finish-args:
-    - --socket=pulseaudio
-    - --socket=fallback-x11
-    - --socket=wayland
-    - --share=ipc
-    - --share=network
-    - --talk-name=org.kde.StatusNotifierWatcher # Tray functionalities on KDE
-    - --talk-name=com.canonical.AppMenu.Registrar
-    - --device=all # Needed for GPU acceleration and the webcam
-    - --filesystem=xdg-videos:ro
-    - --filesystem=xdg-pictures:ro
-    - --filesystem=xdg-download # This and the above two are used for drag-n-drop, and download managing
-    - --filesystem=xdg-run/pipewire-0:ro # Pipewire interfacing
-    - --filesystem=xdg-run/speech-dispatcher:ro # For TTS and VcNarrator
-    - --filesystem=~/.steam # Needed for SteamOS integration, as the XDG OpenURL portal doesn't work properly in Game Mode. We only need ~/.steam/steam.pipe but Flatpak can't correctly mount just that: 'File "/home/deck/.steam/steam.pipe" has unsupported type 0o10000'
-    - --env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons # This is used to show the correct cursor on Wayland
+  - --socket=pulseaudio
+  - --socket=fallback-x11
+  - --socket=wayland
+  - --share=ipc
+  - --share=network
+  - --talk-name=org.kde.StatusNotifierWatcher   # Tray functionalities on KDE
+  - --talk-name=com.canonical.AppMenu.Registrar
+  - --device=all   # Needed for GPU acceleration and the webcam
+  - --filesystem=xdg-videos:ro
+  - --filesystem=xdg-pictures:ro
+  - --filesystem=xdg-download   # This and the above two are used for drag-n-drop, and download managing
+  - --filesystem=xdg-run/pipewire-0:ro   # Pipewire interfacing
+  - --filesystem=xdg-run/speech-dispatcher:ro   # For TTS and VcNarrator
+  - --filesystem=~/.steam   # Needed for SteamOS integration, as the XDG OpenURL portal doesn't work properly in Game Mode. We only need ~/.steam/steam.pipe but Flatpak can't correctly mount just that: 'File "/home/deck/.steam/steam.pipe" has unsupported type 0o10000'
+  - --env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons   # This is used to show the correct cursor on Wayland
 
 modules:
-    - name: Equibop
-      buildsystem: simple
-      build-options:
-          env:
-              SKIP_BUN_DOWNLOAD: "true"
-      build-commands:
-          - tar xzf node_modules.tar.gz
+  - name: Equibop
+    buildsystem: simple
+    build-options:
+      env:
+        SKIP_BUN_DOWNLOAD: 'true'
+    build-commands:
+      - tar xzf node_modules.tar.gz
 
-          - bun-build/bun run build
-          - export PATH="$PWD/bun-build:$PATH" && . /usr/lib/sdk/node20/enable.sh && node_modules/.bin/electron-builder --dir --linux dir --config.electronDist=node_modules/electron/dist
+      - bun-build/bun run build
+      - export PATH="$PWD/bun-build:$PATH" && . /usr/lib/sdk/node20/enable.sh && node_modules/.bin/electron-builder
+        --dir --linux dir --config.electronDist=node_modules/electron/dist
 
-          - |
-              if [ -d "dist/linux-unpacked" ]; then
-                DIST_DIR="dist/linux-unpacked"
-              elif [ -d "dist/linux-arm64-unpacked" ]; then
-                DIST_DIR="dist/linux-arm64-unpacked"
-              else
-                echo "Error: Could not find unpacked directory"
-                exit 1
-              fi
+      - |
+        if [ -d "dist/linux-unpacked" ]; then
+          DIST_DIR="dist/linux-unpacked"
+        elif [ -d "dist/linux-arm64-unpacked" ]; then
+          DIST_DIR="dist/linux-arm64-unpacked"
+        else
+          echo "Error: Could not find unpacked directory"
+          exit 1
+        fi
 
-              if [ "$FLATPAK_ARCH" = "x86_64" ]; then
-                  BUN_PLATFORM="linux-x64"
-              elif [ "$FLATPAK_ARCH" = "aarch64" ]; then
-                  BUN_PLATFORM="linux-arm64"
-              fi
+        if [ "$FLATPAK_ARCH" = "x86_64" ]; then
+            BUN_PLATFORM="linux-x64"
+        elif [ "$FLATPAK_ARCH" = "aarch64" ]; then
+            BUN_PLATFORM="linux-arm64"
+        fi
 
-              mkdir -p "$DIST_DIR/resources/bun/$BUN_PLATFORM/bun-$BUN_PLATFORM"
-              cp bun-build/bun "$DIST_DIR/resources/bun/$BUN_PLATFORM/bun-$BUN_PLATFORM/bun"
-              chmod +x "$DIST_DIR/resources/bun/$BUN_PLATFORM/bun-$BUN_PLATFORM/bun"
+        mkdir -p "$DIST_DIR/resources/bun/$BUN_PLATFORM/bun-$BUN_PLATFORM"
+        cp bun-build/bun "$DIST_DIR/resources/bun/$BUN_PLATFORM/bun-$BUN_PLATFORM/bun"
+        chmod +x "$DIST_DIR/resources/bun/$BUN_PLATFORM/bun-$BUN_PLATFORM/bun"
 
-              install -Dm644 build/icon.svg /app/share/icons/hicolor/scalable/apps/org.equicord.equibop.svg
+        install -Dm644 build/icon.svg /app/share/icons/hicolor/scalable/apps/org.equicord.equibop.svg
 
-              desktop-file-edit --set-key=Exec --set-value="startequibop %U" build/org.equicord.equibop.desktop
-              install -Dm644 build/org.equicord.equibop.desktop /app/share/applications/org.equicord.equibop.desktop
-              install -Dm755 startequibop /app/bin/startequibop
-              install -D build/org.equicord.equibop.metainfo.xml -t /app/share/metainfo/
+        desktop-file-edit --set-key=Exec --set-value="startequibop %U" build/org.equicord.equibop.desktop
+        install -Dm644 build/org.equicord.equibop.desktop /app/share/applications/org.equicord.equibop.desktop
+        install -Dm755 startequibop /app/bin/startequibop
+        install -D build/org.equicord.equibop.metainfo.xml -t /app/share/metainfo/
 
-              mv "$DIST_DIR" /app/bin/equibop
+        mv "$DIST_DIR" /app/bin/equibop
 
-      sources:
-          - type: file
-            path: startequibop
+    sources:
+      - type: file
+        path: startequibop
 
-          - type: archive
-            url: https://github.com/Equicord/Equibop/archive/refs/tags/v3.0.9.tar.gz
-            sha512: f38a53241e441ea1ae01ad5c198bb8ac838a769d21f0e7353c05d7670322d6c218012f510ec8b3e39af71a78e221b4fe36795c281ed443c9b823f2b529f249e3
-            strip-components: 1
-            x-checker-data:
-                type: json
-                url: https://api.github.com/repos/Equicord/Equibop/releases/latest
-                version-query: .tag_name | sub("v"; "")
-                url-query: .tarball_url
-                is-main-source: true
+      - type: archive
+        url: https://api.github.com/repos/Equicord/Equibop/tarball/v3.0.9
+        sha512: d88f7ace44438a4392a7344128bd142e3c8a5a3564818c5c58661130b438b8a2ccec3786adbac685037d74c82248e29298bfd51491f040615e5e30004db7e145
+        strip-components: 1
+        x-checker-data:
+          type: json
+          url: https://api.github.com/repos/Equicord/Equibop/releases/latest
+          version-query: .tag_name | sub("v"; "")
+          url-query: .tarball_url
+          is-main-source: true
 
-          - type: patch
-            path: sandboxFix.patch
+      - type: patch
+        path: sandboxFix.patch
 
-          - type: patch
-            path: gitHash.patch
+      - type: patch
+        path: gitHash.patch
 
-          - type: file
-            url: https://github.com/Equicord/Equibop/releases/download/v3.0.9/node_modules-x64.tar.gz
-            dest-filename: node_modules.tar.gz
-            sha512: fa36abe4378794b78a99dcde687b7377e337624687cf177d1c63e5de7daf48bf3c0f7e40238aa54246b6c0e51c542d52f4456d79b8d44bba46cdc05e41802cf4
-            only-arches: [x86_64]
-            x-checker-data:
-                type: json
-                url: https://api.github.com/repos/Equicord/Equibop/releases/latest
-                version-query: .tag_name | sub("v"; "")
-                url-query:
-                    .assets[] | select(.name == "node_modules-x64.tar.gz")
-                    | .browser_download_url
+      - type: file
+        url: https://github.com/Equicord/Equibop/releases/download/v3.0.9/node_modules-x64.tar.gz
+        dest-filename: node_modules.tar.gz
+        sha512: fa36abe4378794b78a99dcde687b7377e337624687cf177d1c63e5de7daf48bf3c0f7e40238aa54246b6c0e51c542d52f4456d79b8d44bba46cdc05e41802cf4
+        only-arches: [x86_64]
+        x-checker-data:
+          type: json
+          url: https://api.github.com/repos/Equicord/Equibop/releases/latest
+          version-query: .tag_name | sub("v"; "")
+          url-query: .assets[] | select(.name == "node_modules-x64.tar.gz") | .browser_download_url
 
-          - type: file
-            url: https://github.com/Equicord/Equibop/releases/download/v3.0.9/node_modules-arm64.tar.gz
-            dest-filename: node_modules.tar.gz
-            sha512: 4b858fede5fb683b86da6158e227d29292908be4bbf6fd9223ed259dbaf83917c482f0c949f340648dbc6ba31c275ee042f2c4cdde368c44a0e422a352b476d1
-            only-arches: [aarch64]
-            x-checker-data:
-                type: json
-                url: https://api.github.com/repos/Equicord/Equibop/releases/latest
-                version-query: .tag_name | sub("v"; "")
-                url-query:
-                    .assets[] | select(.name == "node_modules-arm64.tar.gz")
-                    | .browser_download_url
+      - type: file
+        url: https://github.com/Equicord/Equibop/releases/download/v3.0.9/node_modules-arm64.tar.gz
+        dest-filename: node_modules.tar.gz
+        sha512: 4b858fede5fb683b86da6158e227d29292908be4bbf6fd9223ed259dbaf83917c482f0c949f340648dbc6ba31c275ee042f2c4cdde368c44a0e422a352b476d1
+        only-arches: [aarch64]
+        x-checker-data:
+          type: json
+          url: https://api.github.com/repos/Equicord/Equibop/releases/latest
+          version-query: .tag_name | sub("v"; "")
+          url-query: .assets[] | select(.name == "node_modules-arm64.tar.gz") | .browser_download_url
 
           # Electron binaries for building
-          - type: archive
-            url: https://github.com/electron/electron/releases/download/v38.4.0/electron-v38.4.0-linux-x64.zip
-            sha512: b20ed3f62b408b69b0d64413b13efd3da3cffa7f16d7c5d658ada05f7975961c9127711cf2dab2023a2de6d9c5085dd83b35f6de3e1c602e283b9703642ea3d7
-            dest: node_modules/electron/dist
-            only-arches: [x86_64]
+      - type: archive
+        url: https://github.com/electron/electron/releases/download/v38.4.0/electron-v38.4.0-linux-x64.zip
+        sha512: b20ed3f62b408b69b0d64413b13efd3da3cffa7f16d7c5d658ada05f7975961c9127711cf2dab2023a2de6d9c5085dd83b35f6de3e1c602e283b9703642ea3d7
+        dest: node_modules/electron/dist
+        only-arches: [x86_64]
 
-          - type: archive
-            url: https://github.com/electron/electron/releases/download/v38.4.0/electron-v38.4.0-linux-arm64.zip
-            sha512: 729ed9f30e1bf0e4e108474c6356b0437379268c57791ebb4cadaaffc273dc1f585fd7a7e4e4ebbe23f801623feca0e5d4443dc8f5ce4080de17b034d221fee4
-            dest: node_modules/electron/dist
-            only-arches: [aarch64]
+      - type: archive
+        url: https://github.com/electron/electron/releases/download/v38.4.0/electron-v38.4.0-linux-arm64.zip
+        sha512: 729ed9f30e1bf0e4e108474c6356b0437379268c57791ebb4cadaaffc273dc1f585fd7a7e4e4ebbe23f801623feca0e5d4443dc8f5ce4080de17b034d221fee4
+        dest: node_modules/electron/dist
+        only-arches: [aarch64]
 
-          - type: archive
-            url: https://github.com/oven-sh/bun/releases/download/bun-v1.3.1/bun-linux-x64.zip
-            sha512: 1fd367254ccff89163b32ee8bf76b7f013855043bf828d36300aaeef95b72139ed6afdab4446e11e85b56b4a57cfd45a2c4d02460a5f1172e35493ad603fc010
-            dest: bun-build
-            only-arches: [x86_64]
-            x-checker-data:
-                type: json
-                url: https://api.github.com/repos/oven-sh/bun/releases/latest
-                version-query: .tag_name | sub("bun-v"; "")
-                url-query: .assets[] | select(.name == "bun-linux-x64.zip") | .browser_download_url
+      - type: archive
+        url: https://github.com/oven-sh/bun/releases/download/bun-v1.3.1/bun-linux-x64.zip
+        sha512: 1fd367254ccff89163b32ee8bf76b7f013855043bf828d36300aaeef95b72139ed6afdab4446e11e85b56b4a57cfd45a2c4d02460a5f1172e35493ad603fc010
+        dest: bun-build
+        only-arches: [x86_64]
+        x-checker-data:
+          type: json
+          url: https://api.github.com/repos/oven-sh/bun/releases/latest
+          version-query: .tag_name | sub("bun-v"; "")
+          url-query: .assets[] | select(.name == "bun-linux-x64.zip") | .browser_download_url
 
-          - type: archive
-            url: https://github.com/oven-sh/bun/releases/download/bun-v1.3.1/bun-linux-aarch64.zip
-            sha512: 28f96904bcf24f133fedeb0995970ad4f085d16bc700dea46a66c1736074c642034edd445c03153b966cada551df8dd4c86fd85f03a4f820963666da6ea020c5
-            dest: bun-build
-            only-arches: [aarch64]
-            x-checker-data:
-                type: json
-                url: https://api.github.com/repos/oven-sh/bun/releases/latest
-                version-query: .tag_name | sub("bun-v"; "")
-                url-query: .assets[] | select(.name == "bun-linux-aarch64.zip") | .browser_download_url
+      - type: archive
+        url: https://github.com/oven-sh/bun/releases/download/bun-v1.3.1/bun-linux-aarch64.zip
+        sha512: 28f96904bcf24f133fedeb0995970ad4f085d16bc700dea46a66c1736074c642034edd445c03153b966cada551df8dd4c86fd85f03a4f820963666da6ea020c5
+        dest: bun-build
+        only-arches: [aarch64]
+        x-checker-data:
+          type: json
+          url: https://api.github.com/repos/oven-sh/bun/releases/latest
+          version-query: .tag_name | sub("bun-v"; "")
+          url-query: .assets[] | select(.name == "bun-linux-aarch64.zip") | .browser_download_url
